In [ ]:
import pandas as pd
import numpy as np
from contourpy import max_threads

Write a Python program using Pandas to create a DataFrame from the given data and calculate the average rating of movies directed by Christopher Nolan.



data = {

    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],

    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],

    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]

}

In [ ]:

data = {

    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],

    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],

    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]

}
df = pd.DataFrame(data)
average = df['Rating'].mean()
print(average)

Given the following DataFrame, write a Python program using Pandas to extract all rows where the price is greater than or equal to 20,000 and sort them in descending order by price.


data = {

    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],

    'Price': [25000, 12000, 8000, 22000, 5000]

}


df = pd.DataFrame(data)

In [ ]:
data = {

    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],

    'Price': [25000, 12000, 8000, 22000, 5000]

}


df = pd.DataFrame(data)
df_filter = df[df['Price']>= 20000]
print(df_filter)
sortdf = df_filter.sort_values(by="Price", ascending=False)
print(sortdf)

Write a Python program using Pandas to create a DataFrame from the given data and find the total revenue and average price of items sold in each store.


data = {

    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],

    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],

    'Price': [50, 20, 30, 60, 55, 22, 33, 65],

    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]

}

In [ ]:

data = {

    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],

    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],

    'Price': [50, 20, 30, 60, 55, 22, 33, 65],

    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]

}
df = pd.DataFrame(data)
df['Revenue'] = df['Price']*df['Quantity']
result = df.groupby("Store").agg(
    Total_Revenue=("Revenue", "sum"),
    Average_Price=("Quantity", "sum"))

result["Average_Price"] = result["Total_Revenue"]/result["Average_Price"]
print(df)
print(result)

Write a Python program using Pandas to create a DataFrame from the given data and calculate the total amount spent by each customer.


data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}

In [ ]:

data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}
df = pd.DataFrame(data)
df["Amount"] = df["Price"]*df["Quantity"]
grouped = df.groupby('Customer').agg(Total_Spent = ("Amount", "sum"))

print(grouped)
print(df)

Write a Python program using Pandas to create a DataFrame from the given data and find the month with the highest average temperature.


data = {

    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]

}


df = pd.DataFrame(data)

In [ ]:
data = {

    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]

}

df = pd.DataFrame(data)
max_Tidx = df['Temperature'].idxmax()
hottest = df.loc[max_Tidx, 'Month']
print(hottest)

Write a Python program using Pandas to create a DataFrame from the given data and find the total amount spent per item, as well as the total amount spent by all customers.


data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}

In [ ]:

data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}
df = pd.DataFrame(data)
df["Amount"] = df["Price"]*df["Quantity"]
grouped = df.groupby('Item').agg(Total_Spent = ("Amount", "sum"))
group2 = df.groupby('Customer').agg(Total_Spent = ("Amount", "sum"))
print(grouped)
print(group2)

 Write a Python program using Pandas to create a DataFrame from the given data and calculate the monthly average temperature difference between two cities.


data = {

    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],

    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]

}


df = pd.DataFrame(data)

In [ ]:
data = {

    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],

    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],

    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]

}

df = pd.DataFrame(data)
df["Delta_T"] = (df["City_A_Temp"] - df["City_B_Temp"]).abs()
average = df["Delta_T"].sum()/df["Month"].count()
print(average)
print(df)